In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('/workspaces/projects/Credit_Classification_End_to_End/cleaned.csv')
df.head()

,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Num_of_Delayed_Payment,Credit_Utilization_Ratio,Payment_of_Min_Amount,Total_EMI_per_month,Credit_Score,Type_of_Loan,Delay_from_due_date,Customer_ID,Credit_History_Age_Formated
0,23.0,19114.12,3.0,4.0,7.0,26.822620,No,49.574949,Good,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,CUS_0xd40,265.0
1,23.0,19114.12,3.0,4.0,6.0,31.944960,No,49.574949,Good,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,CUS_0xd40,266.0
2,23.0,19114.12,3.0,4.0,7.0,28.609352,No,49.574949,Good,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,CUS_0xd40,267.0
3,23.0,19114.12,3.0,4.0,4.0,31.377862,No,49.574949,Good,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,CUS_0xd40,268.0
4,23.0,19114.12,3.0,4.0,6.0,24.797347,No,49.574949,Good,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,CUS_0xd40,269.0

I want to read the column `Type_of_loan` and separate all loans, so I can make the dummies. First I collect the different types of loans in an array, then I just check if a customer has that loan, if they do the loan column will receive a value of 1, otherwise is 0.

In [13]:
loan_types = []
for index in df.index:
    temp = df.Type_of_Loan[index].replace('and ', '').split(', ')
    for i in temp: #loan in temp array
        if i not in loan_types: #if loan is not in loan_types
            loan_types.append(i) #add it

In [14]:
for loan in loan_types:
    df[loan.replace(' ', '_')] = 0 #create the loan column in the df with 0
    for index in df.index:
        temp = df.Type_of_Loan[index].replace('and ', '').split(', ')
        if loan in temp:
            df.loc[index, loan.replace(' ', '_')] = 1

In [15]:
df.iloc[:,-9:].head()

,Auto_Loan,Credit-Builder_Loan,Personal_Loan,Home_Equity_Loan,Not_Specified,Mortgage_Loan,Student_Loan,Debt_Consolidation_Loan,Payday_Loan
0,1,1,1,1,0,0,0,0,0
1,1,1,1,1,0,0,0,0,0
2,1,1,1,1,0,0,0,0,0
3,1,1,1,1,0,0,0,0,0
4,1,1,1,1,0,0,0,0,0

In [16]:
df.head().T

,0,1,2,3,4
Age,23.0,23.0,23.0,23.0,23.0
Annual_Income,19114.12,19114.12,19114.12,19114.12,19114.12
Num_Bank_Accounts,3.0,3.0,3.0,3.0,3.0
Num_Credit_Card,4.0,4.0,4.0,4.0,4.0
Num_of_Delayed_Payment,7.0,6.0,7.0,4.0,6.0
Credit_Utilization_Ratio,26.82262,31.94496,28.609352,31.377862,24.797347
Payment_of_Min_Amount,No,No,No,No,No
Total_EMI_per_month,49.574949,49.574949,49.574949,49.574949,49.574949
Credit_Score,Good,Good,Good,Good,Good
Type_of_Loan,"Auto Loan, Credit-Builder Loan, Personal Loan,...","Auto Loan, Credit-Builder Loan, Personal Loan,...","Auto Loan, Credit-Builder Loan, Personal Loan,...","Auto Loan, Credit-Builder Loan, Personal Loan,...","Auto Loan, Credit-Builder Loan, Personal Loan,..."
Delay_from_due_date,3,-1,3,5,6
Customer_ID,CUS_0xd40,CUS_0xd40,CUS_0xd40,CUS_0xd40,CUS_0xd40
Credit_History_Age_Formated,265.0,266.0,267.0,268.0,269.0
Auto_Loan,1,1,1,1,1
Credit-Builder_Loan,1,1,1,1,1
Personal_Loan,1,1,1,1,1
Home_Equity_Loan,1,1,1,1,1
Not_Specified,0,0,0,0,0
Mortgage_Loan,0,0,0,0,0
Student_Loan,0,0,0,0,0
Debt_Consolidation_Loan,0,0,0,0,0
Payday_Loan,0,0,0,0,0

Just save the dataset so we can start with the new features in the next notebook!

In [17]:
df.to_csv('final.csv', index=False)