In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df= pd.read_excel("/workspaces/projects/Flight_Delay_End_to_End/Data_Train.xlsx")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [4]:
df.isna().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [5]:
df.dropna(inplace=True)

In [6]:
df.isna().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [7]:
df['Date_of_Journey']= pd.to_datetime(df['Date_of_Journey'])
df['Month']= df['Date_of_Journey'].dt.month

/tmp/ipykernel_16016/585817374.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date_of_Journey']= pd.to_datetime(df['Date_of_Journey'])

In [8]:
#df= df.drop('Date_of_Journey', axis=1)

In [9]:
df.head(10)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Month
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,3
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,5
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,6
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,5
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,3
5,SpiceJet,2019-06-24,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873,6
6,Jet Airways,2019-03-12,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25 13 Mar,15h 30m,1 stop,In-flight meal not included,11087,3
7,Jet Airways,2019-03-01,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05 02 Mar,21h 5m,1 stop,No info,22270,3
8,Jet Airways,2019-03-12,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25 13 Mar,25h 30m,1 stop,In-flight meal not included,11087,3
9,Multiple carriers,2019-05-27,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625,5

In [10]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [11]:
stops={'non-stop':0, '2 stops':2, '1 stop':1, '3 stops':3, '4 stops':4}

In [12]:
df.drop('Additional_Info', axis=1)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Price,Month
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,3897,3
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,7662,5
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,13882,6
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,6218,5
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,13302,3
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,2019-04-09,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,4107,4
10679,Air India,2019-04-27,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,4145,4
10680,Jet Airways,2019-04-27,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,7229,4
10681,Vistara,2019-03-01,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,12648,3
10682,Air India,2019-05-09,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,11753,5

In [13]:
# assigning numbers to the Total stops column
stops_list=list(df['Total_Stops'])
new_stops=[]
for i in stops_list:
    if i in stops:
        new_stops.append(stops[i])

In [14]:
df['Total_Stops']=new_stops

In [15]:
#dropping additional info columns as we don't need it
df=df.drop('Additional_Info', axis=1)

In [16]:
#making a column which has day of the month
df['Day']=df['Date_of_Journey'].dt.day

In [17]:
df= df.drop('Date_of_Journey',axis=1)

In [18]:
df=df.drop('Route',axis=1)

In [19]:
list(df['Duration'])[0].split(" ")

['2h', '50m']

In [20]:
print(list(df['Duration'])[0].split(" ")[0])
print(list(df['Duration'])[0].split(" ")[1])

2h
50m

In [21]:
duration_list= list(df['Duration'])
duration_hour= []
duration_minute=[]
for i in duration_list:
    
    if "h" in i.split(" ")[0]:
        duration_hour.append(i.split(" ")[0].replace("h",""))
    else:
        duration_hour.append(0)

In [22]:
df['Duration_Hour']=duration_hour

In [23]:
df= df.drop('Duration', axis=1)
df= df.drop('Arrival_Time', axis=1)
df= df.drop('Dep_Time', axis=1)
df

,Airline,Source,Destination,Total_Stops,Price,Month,Day,Duration_Hour
0,IndiGo,Banglore,New Delhi,0,3897,3,24,2
1,Air India,Kolkata,Banglore,2,7662,5,1,7
2,Jet Airways,Delhi,Cochin,2,13882,6,9,19
3,IndiGo,Kolkata,Banglore,1,6218,5,12,5
4,IndiGo,Banglore,New Delhi,1,13302,3,1,4
...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,0,4107,4,9,2
10679,Air India,Kolkata,Banglore,0,4145,4,27,2
10680,Jet Airways,Banglore,Delhi,0,7229,4,27,3
10681,Vistara,Banglore,New Delhi,0,12648,3,1,2
10682,Air India,Delhi,Cochin,2,11753,5,9,8

In [24]:
#segregating data into X and Y
X= df.drop('Price', axis=1)
Y=df['Price']

In [25]:
#Converting X and Y into Train and test data

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X,Y,test_size=0.1, random_state=0)

In [26]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn import metrics

In [28]:
# label encoding
cf= ColumnTransformer([('trf',OneHotEncoder(drop='first'), 
['Airline','Source','Destination'])],remainder='passthrough')

In [29]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor #70
from sklearn.ensemble import RandomForestRegressor #72%


pipe= Pipeline(steps=[
    ('step1',cf),
    ('step2', RandomForestRegressor())
])

In [30]:
pipe.fit(x_train,y_train)

/workspaces/projects/.venv/lib/python3.12/site-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first'),
                                                  ['Airline', 'Source',
                                                   'Destination'])])),
                ('step2', RandomForestRegressor())])

In [31]:
y_pred= pipe.predict(x_test)

In [32]:
print(r2_score(y_test,y_pred))
df

0.725072860137741

,Airline,Source,Destination,Total_Stops,Price,Month,Day,Duration_Hour
0,IndiGo,Banglore,New Delhi,0,3897,3,24,2
1,Air India,Kolkata,Banglore,2,7662,5,1,7
2,Jet Airways,Delhi,Cochin,2,13882,6,9,19
3,IndiGo,Kolkata,Banglore,1,6218,5,12,5
4,IndiGo,Banglore,New Delhi,1,13302,3,1,4
...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,0,4107,4,9,2
10679,Air India,Kolkata,Banglore,0,4145,4,27,2
10680,Jet Airways,Banglore,Delhi,0,7229,4,27,3
10681,Vistara,Banglore,New Delhi,0,12648,3,1,2
10682,Air India,Delhi,Cochin,2,11753,5,9,8

In [33]:
pipe.predict(pd.DataFrame({"Airline":['Air Asia'],"Source":['Kolkata'],"Destination":['Banglore'],
                           "Total_Stops":[0],"Month":[9],"Day":[4],"Duration_Hour":[2]}))

array([4446.06583333])

In [34]:
import pickle

with open("Flight.pkl", "wb") as file:
    pickle.dump(pipe, file)

In [1]:
import sklearn
print(sklearn.__version__)

1.6.1